import os

# We build the content as a list of lines to avoid "Triple Quote Hell"
lines = []

# --- HEADER & BADGES ---
lines.append("# Automatrix: End-to-End Supply Chain ETL Automation")
lines.append("")
lines.append("![Python](https://img.shields.io/badge/Python-3.9-blue?style=for-the-badge&logo=python&logoColor=white)")
lines.append("![PostgreSQL](https://img.shields.io/badge/PostgreSQL-17-336791?style=for-the-badge&logo=postgresql&logoColor=white)")
lines.append("![Power BI](https://img.shields.io/badge/Power_BI-Fabric-F2C811?style=for-the-badge&logo=powerbi&logoColor=black)")
lines.append("![Pandas](https://img.shields.io/badge/Pandas-ETL-150458?style=for-the-badge&logo=pandas&logoColor=white)")
lines.append("")

# --- EXECUTIVE SUMMARY ---
lines.append("## 📖 Executive Summary")
lines.append("")
lines.append("**Automatrix** is a full-stack data engineering solution designed to bridge the gap between legacy ERP systems and modern Business Intelligence.")
lines.append("")
lines.append("Many manufacturing sectors still rely on legacy desktop ERPs (like Lighthouse ERP) that lack API connectivity. This project automates the manual extraction of daily data using **RPA (Robotic Process Automation)**, processes it via Python to handle duplicates and updates (SCD Type 1), and loads it into an on-premise PostgreSQL warehouse. The final output is a Power BI Fabric dashboard used for daily procurement and inventory decision-making.")
lines.append("")
lines.append("**Business Impact:**")
lines.append("* **Zero Manual Entry:** Replaced 2+ hours of daily manual Excel export/cleaning with a fully automated script.")
lines.append("* **Data Latency:** Reduced reporting lag from 24 hours to <1 hour (Daily 10:00 AM Run).")
lines.append("* **Inventory Visibility:** Enabled 80/20 Pareto analysis to identify high-value stock items.")
lines.append("")
lines.append("---")
lines.append("")

# --- ARCHITECTURE ---
lines.append("## 🏗️ System Architecture")
lines.append("")
lines.append("![ETL Pipeline Architecture](architecture/etl_pipeline_diagram.png)")
lines.append("")
lines.append("**The Data Pipeline Flow:**")
lines.append("1. **Extraction (10:00 AM):** A Python script (`pyautogui` + `pywinauto`) wakes the VM, logs into the legacy ERP client, and navigates UI menus to export raw CSVs for Purchase Orders, GRN, and Issues.")
lines.append("2. **Transformation (10:15 AM):** `Pandas` cleans the data, parses dates, and formats columns.")
lines.append("3. **Loading (Upsert Logic):** Data is pushed to **PostgreSQL**. A custom \"Upsert\" function checks for existing records:")
lines.append("   * *New Records* → INSERT")
lines.append("   * *Existing Records* → UPDATE (SCD Type 1) to reflect changes in quantity or status.")
lines.append("4. **Reporting (11:00 AM):** Power BI On-Premises Data Gateway refreshes the dashboard.")
lines.append("5. **Alerting:** SMTP email triggers send a status report (Success/Fail) with attached CSVs to stakeholders.")
lines.append("")
lines.append("---")
lines.append("")

# --- DASHBOARD SECTION ---
lines.append("## 📊 Dashboard & Reporting")
lines.append("")
lines.append("The data feeds into a multi-page Power BI report. Below are the results generated from the pipeline.")
lines.append("")
lines.append("### 1. Executive Procurement Analysis")
lines.append("![PO Supplier Analysis](screenshots/dashboard_po_analysis.jpg)")
lines.append("*Breakdown of open Purchase Orders by supplier and department. Highlights the total liability (₹2.39 Cr) and average cycle time.*")
lines.append("")
lines.append('<details>')
lines.append('<summary><b>🔻 Click to view Page 2: GRN & Delivery Analysis</b></summary>')
lines.append("")
lines.append("![GRN Analysis](screenshots/dashboard_grn_analysis.jpg)")
lines.append("*Tracks the conversion of Orders to Goods Receipt Notes (GRN). Monitors the ratio of Revenue Stock vs. Capital Stock.*")
lines.append('</details>')
lines.append("")
lines.append('<details>')
lines.append('<summary><b>🔻 Click to view Page 3: Strategic 80/20 Inventory Control</b></summary>')
lines.append("")
lines.append("![Pareto Analysis](screenshots/dashboard_pareto.jpg)")
lines.append("*Pareto analysis identifying the critical 20% of SKUs that drive 55% of inventory value.*")
lines.append('</details>')
lines.append("")
lines.append('<details>')
lines.append('<summary><b>🔻 Click to view Page 4: Data Lineage Summary</b></summary>')
lines.append("")
lines.append("![Summary View](screenshots/dashboard_summary.jpg)")
lines.append("*Tabular view used for auditing specific transaction IDs against the ERP.*")
lines.append('</details>')
lines.append("")
lines.append("---")
lines.append("")

# --- ARTIFACTS SECTION (New!) ---
lines.append("## 📂 Project Artifacts")
lines.append("You can access the source files and generated reports here:")
lines.append("")
lines.append("| File Type | Location | Description |")
lines.append("| :--- | :--- | :--- |")
lines.append("| **Power BI File** | [`dashboards/Supply_Chain_Analysis.pbix`](dashboards/) | The raw source file containing the DAX measures and data model. |")
lines.append("| **Sample Report** | [`reports/Executive_Supply_Chain_Report.docx`](reports/) | An automated Word document generated daily for stakeholders. |")
lines.append("| **SQL Schema** | [`sql/init_schema.sql`](sql/init_schema.sql) | The PostgreSQL table definitions and View logic. |")
lines.append("")
lines.append("---")
lines.append("")

# --- TECHNICAL IMPLEMENTATION ---
lines.append("## 💻 Technical Implementation")
lines.append("")
lines.append("### 1. The \"Upsert\" Logic (PostgreSQL + Python)")
lines.append("One of the main challenges was handling data that changes retroactively (e.g., a PO quantity is revised). Simply appending data would create duplicates. I implemented a robust `INSERT ... ON CONFLICT DO UPDATE` strategy.")
lines.append("")

lines.append("```python")
lines.append("# snippet from src/etl_process.py")
lines.append('insert_sql = """') 
lines.append("INSERT INTO pur_order_daily_main (")
lines.append("    order_date, item_code, order_number, order_value, ")
lines.append("    bal_qty, rate, department, cost_project")
lines.append(") VALUES (%s, %s, %s, %s, %s, %s, %s, %s)")
lines.append("ON CONFLICT (order_date, item_code, order_number, department, cost_project)")
lines.append("DO UPDATE SET")
lines.append("    order_value = EXCLUDED.order_value,")
lines.append("    bal_qty = EXCLUDED.bal_qty,")
lines.append("    rate = EXCLUDED.rate;")
lines.append('"""') 
lines.append("```")

lines.append("")
lines.append("### 2. RPA for Legacy ERP")
lines.append("Since the ERP has no API, I used `pyautogui` for visual navigation and `pywinauto` for window handling.")
lines.append("")
lines.append("```python")
lines.append("# snippet from src/automation.py")
lines.append("def focus_lighthouse_window():")
lines.append("    try:")
lines.append("        windows = gw.getWindowsWithTitle('Lighthouse ERP')")
lines.append("        window = windows[0]")
lines.append("        window.activate() ")
lines.append("        ")
lines.append("        # Automates the \"Print\" -> \"Export to CSV\" flow")
lines.append("        pyautogui.click(615, 573) ")
lines.append("        time.sleep(3)")
lines.append("        ")
lines.append("        # ... navigation logic")
lines.append("    except Exception as e:")
lines.append("        print(f\"Error: {e}\")")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")

# --- INSTALLATION ---
lines.append("## 🛠️ Installation & Setup")
lines.append("> **Note:** Because this project relies on specific local legacy software (Lighthouse ERP) and a Windows VM, the extraction scripts cannot be run directly on a standard machine. However, the Database and Transformation logic can be tested.")
lines.append("")
lines.append("### Clone the Repo")
lines.append("```bash")
lines.append("git clone [https://github.com/ShubhrajyotiPoddar/automatrix-ETL.git](https://github.com/ShubhrajyotiPoddar/automatrix-ETL.git)")
lines.append("cd automatrix-ETL")
lines.append("```")
lines.append("")
lines.append("### Install Dependencies")
lines.append("```bash")
lines.append("pip install -r requirements.txt")
lines.append("```")
lines.append("")
lines.append("### Database Setup")
lines.append("I have provided a schema initialization script to spin up the Postgres structure (Tables + Views) with dummy data.")
lines.append("```bash")
lines.append("# Run the SQL script in your local Postgres instance")
lines.append("psql -U postgres -d supply_chain_db -f sql/init_schema.sql")
lines.append("```")
lines.append("")
lines.append("---")
lines.append("")

# --- SECURITY ---
lines.append("## ⚠️ Security & Privacy Note")
lines.append("This repository demonstrates a portfolio project. To ensure security:")
lines.append("* **Fake Data:** All data shown in screenshots and the database seed is randomized/anonymized (sanitized). No real company PII or financial data is present.")
lines.append("* **Redacted Credentials:** Database passwords, ERP logins, and Server IPs in the source code have been replaced with placeholders (e.g., `REDACTED_CREDENTIAL`).")
lines.append("")
lines.append("In a production environment, these are managed via `os.environ` variables or Azure Key Vault.")
lines.append("")
lines.append("---")
lines.append("")

# --- AUTHOR ---
lines.append("## 👤 Author")
lines.append("**Shubhrajyoti Poddar** Data Engineer | BI Developer")
lines.append("[LinkedIn Profile](https://www.linkedin.com/in/shubhrajyoti-poddar-506752390/)")

# --- WRITE TO FILE ---
try:
    with open("README.md", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("✅ Successfully created README.md")
except Exception as e:
    print(f"❌ Error creating file: {e}")